symfonyProject/src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank
     */
    private $nom_e;

    /**
     * @ORM\Column(type="date")
     * @Assert\GreaterThanOrEqual(value = "today")
     */
    private $date_deb;

    /**
     * @ORM\Column(type="date")
     *  @Assert\GreaterThanOrEqual(value = "today")
     * @Assert\Expression(
     *     "this.getDateFin() >= this.getDateDeb()",
     *     message="Verifier votre date"
     * )
     * )

     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_e;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank
     */
    private $prix_e;

    /**
     * @ORM\ManyToOne(targetEntity=CategorieE::class, inversedBy="evenements")
     * @ORM\JoinColumn(nullable=false)
     *
     */
    private $categoryId;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rating;

    /**
     * @ORM\OneToMany(targetEntity=CommandeE::class, mappedBy="evenement")
     */
    private $commandeEs;

    public function __construct()
    {
        $this->commandeEs = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomE(): ?string
    {
        return $this->nom_e;
    }

    public function setNomE(string $nom_e): self
    {
        $this->nom_e = $nom_e;

        return $this;
    }

    public function getDateDeb(): ?\DateTimeInterface
    {
        return $this->date_deb;
    }

    public function setDateDeb(\DateTimeInterface $date_deb): self
    {
        $this->date_deb = $date_deb;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getImageE(): ?string
    {
        return $this->image_e;
    }

    public function setImageE(string $image_e): self
    {
        $this->image_e = $image_e;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixE(): ?float
    {
        return $this->prix_e;
    }

    public function setPrixE(float $prix_e): self
    {
        $this->prix_e = $prix_e;

        return $this;
    }

    public function getCategoryId(): ?CategorieE
    {
        return $this->categoryId;
    }

    public function setCategoryId(?CategorieE $categoryId): self
    {
        $this->categoryId = $categoryId;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(?int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    /**
     * @return Collection<int, CommandeE>
     */
    public function getCommandeEs(): Collection
    {
        return $this->commandeEs;
    }

    public function addCommandeE(CommandeE $commandeE): self
    {
        if (!$this->commandeEs->contains($commandeE)) {
            $this->commandeEs[] = $commandeE;
            $commandeE->setEvenement($this);
        }

        return $this;
    }

    public function removeCommandeE(CommandeE $commandeE): self
    {
        if ($this->commandeEs->removeElement($commandeE)) {
            // set the owning side to null (unless already changed)
            if ($commandeE->getEvenement() === $this) {
                $commandeE->setEvenement(null);
            }
        }

        return $this;
    }
}

symfonyProject/src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_e',TextType::class,[

                'constraints' =>[
                    new NotBlank(),
                ]
            ])
            ->add('date_deb' ,DateType::class, [
        'widget' => 'single_text',
        'constraints'=>[
            new NotBlank()
        ],
        // this is actually the default format for single_text
        'format' => 'yyyy-MM-dd',])

            ->add('date_fin' ,DateType::class, [
                'widget' => 'single_text',
                'constraints'=>[
                    new NotBlank()
                ],
                // this is actually the default format for single_text
                'format' => 'yyyy-MM-dd',])

            ->add('description')
            ->add('prix_e')
            ->add('categoryId',EntityType::class,array(
                'class' => 'App:CategorieE',
                'mapped' => false,
                'constraints'=>[
                    new NotBlank()
                ]
            ))

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

symfonyProject/src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\File;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    /**
     * @IsGranted ("ROLE_USER")
     * @Route("/new", name="evenement_new", methods={"GET", "POST"})
     */

    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement)
            ->add('image_e',FileType::class,[
                'mapped'=>false,
                'required'=>true,
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Only images',
                    ])
                ],
            ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image_e')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($image) {
                $newFilename = uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('image_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $evenement->setImageE($newFilename);
            }

            $idCat = $form->get('categoryId')->getData();
            $evenement->setCategoryId($idCat);
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/add", name="evenement_add", methods={"GET", "POST"})
     */

    public function add (Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement)
            ->add('image_e',FileType::class,[
                'mapped'=>false,
                'required'=>true,
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Only images',
                    ])
                ],
            ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image_e')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($image) {
                $newFilename = uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('image_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $evenement->setImageE($newFilename);
            }

            $idCat = $form->get('categoryId')->getData();
            $evenement->setCategoryId($idCat);
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_afficher', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/add_back.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/show/{id}", name="evenement_showsingle", methods={"GET"})
     */
    public function showEvent(Evenement $evenement): Response
    {
        return $this->render('evenement/singleevent.html.twig', [
            'evenement' => $evenement,
        ]);
    }


 /*   /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    /*public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }*/




    /**
     * @Route("/afficher_back", name="evenement_afficher", methods={"GET"})
     */
    public function showBack(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/show_back.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }



    /**
     * @IsGranted ("ROLE_USER")
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement)
            ->add('image_e',FileType::class,[
                'mapped'=>false,
                'required'=>false,
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Only images',
                    ])
                ],
            ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image_e')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($image) {
                $newFilename = uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('image_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $evenement->setImageE($newFilename);
            }
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}/edit_back", name="evenement_editBack", methods={"GET", "POST"})
     */
    public function editBack (Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement)
            ->add('image_e',FileType::class,[
                'mapped'=>false,
                'required'=>false,
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/*',
                        ],
                        'mimeTypesMessage' => 'Only images',
                    ])
                ],
            ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image = $form->get('image_e')->getData();

            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
            if ($image) {
                $newFilename = uniqid().'.'.$image->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $image->move(
                        $this->getParameter('image_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $evenement->setImageE($newFilename);
            }

symfonyProject/templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement index{% endblock %}
{% block extracss %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet"/>
    <link href="/FRONT/css/star-rating.css" rel="stylesheet"/>
    <link href="/FRONT/css/star-rating-demo.css" rel="stylesheet"/>

{% endblock %}
{% set nearEventsTotal = 0 %}
{% for evenement in evenements %}
    {% set datePost = evenement.dateDeb|date('d-m-Y') %}
    {% set today = "now"|date('d-m-Y') %}
    {% set difference = date(today).diff(date(datePost)) %}
    {% set leftDays = difference.days %}
    {% if leftDays < 7 and leftDays >-1 %}
        {% set nearEventsTotal = nearEventsTotal + 1 %}
    {% endif %}
{% endfor %}
{% block body %}

    <!--start section-->
    <section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img14">

        <div class="nicdark_filter greydark">

            <!--start nicdark_container-->
            <div class="nicdark_container nicdark_clearfix">

                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>

                <div class="nicdark_space70"></div> <!--for header 1-->

                <div class="grid grid_6">
                    <h1 class="white subtitle">Nos événements</h1>
                </div>
                <div class="grid grid_6 nicdark_displaynone_responsive">
                    <div class="nicdark_space5"></div>
                    <h4 class="white right subtitle">Evenements<span
                                class="nicdark_marginleft10 nicdark_marginright10 grey2">|</span><a class="white"
                                                                                                    href="{{ path('evenement_new') }}">Ajouter</a>
                    </h4>
                </div>

                <div class="nicdark_space40"></div>
                <div class="nicdark_space40"></div>

            </div>
            <!--end nicdark_container-->

        </div>

    </section>
    <!--end section-->

    <!--start section-->
    <section class="nicdark_section">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">


            <div class="nicdark_space50"></div>


            <div class="nicdark_space10"></div>

            {% for evenement in evenements %}
                <div class="grid grid_3">

                    <div class="nicdark_archive1 nicdark_border_grey nicdark_sizing nicdark_bg_white  ">

                        <img alt="" src="{{ asset('uploads/image/' ~ evenement.imageE) }}">

                        <div class="nicdark_textevidence nicdark_bg_greydark center">
                            <h4 class="white nicdark_margin20">{{ evenement.nomE }}</h4>
                        </div>

                        <div class="nicdark_textevidence nicdark_bg_red center">
                            <h5 class="white nicdark_margin10">{{ evenement.dateDeb|date("m/d/Y") }}</h5>
                        </div>

                        <div class="nicdark_textevidence center">
                            <div class="nicdark_margin20">
                                <h5 class="nicdark_margin10 nourRatingFinal">
                                    Rating: {% if evenement.rating is not empty %}{{ evenement.rating }}{% else %}Pas de rating{% endif %}</h5>

                                <div style="padding-left: 20%;">
                                <span class="gl-star-rating">
                            <select id="glsr-prebuilt" class="star-rating-prebuilt">
                                <option value="">Rate us</option>
                                <option value="5">5 Stars</option>
                                <option value="4">4 Stars</option>
                                <option value="3">3 Stars</option>
                                <option value="2">2 Stars</option>
                                <option value="1">1 Star</option>
                            </select>
                            <span class="gl-star-rating--stars" eventId="{{ evenement.id }}">
                            <span data-value="1" class="starNour"><svg xmlns="http://www.w3.org/2000/svg"
                                                                       viewBox="0 0 24 24" class="gl-emote"
                                                                       style="pointer-events: none;"><circle
                                            class="gl-emote-bg" fill="#FFA98D" cx="12" cy="12" r="10"></circle><path
                                            fill="#393939"
                                            d="M12 14.6c1.48 0 2.9.38 4.15 1.1a.8.8 0 01-.79 1.39 6.76 6.76 0 00-6.72 0 .8.8 0 11-.8-1.4A8.36 8.36 0 0112 14.6zm4.6-6.25a1.62 1.62 0 01.58 1.51 1.6 1.6 0 11-2.92-1.13c.2-.04.25-.05.45-.08.21-.04.76-.11 1.12-.18.37-.07.46-.08.77-.12zm-9.2 0c.31.04.4.05.77.12.36.07.9.14 1.12.18.2.03.24.04.45.08a1.6 1.6 0 11-2.34-.38z"></path></svg></span>
                            <span data-value="2" class="starNour"><svg xmlns="http://www.w3.org/2000/svg"
                                                                       viewBox="0 0 24 24" class="gl-emote"
                                                                       style="pointer-events: none;"><circle
                                            class="gl-emote-bg" fill="#FFC385" cx="12" cy="12" r="10"></circle><path
                                            fill="#393939"
                                            d="M12 14.8c1.48 0 3.08.28 3.97.75a.8.8 0 11-.74 1.41A8.28 8.28 0 0012 16.4a9.7 9.7 0 00-3.33.61.8.8 0 11-.54-1.5c1.35-.48 2.56-.71 3.87-.71zM15.7 8c.25.31.28.34.51.64.24.3.25.3.43.52.18.23.27.33.56.7A1.6 1.6 0 1115.7 8zM8.32 8a1.6 1.6 0 011.21 2.73 1.6 1.6 0 01-2.7-.87c.28-.37.37-.47.55-.7.18-.22.2-.23.43-.52.23-.3.26-.33.51-.64z"></path></svg></span>
                            <span data-value="3" class="starNour"><svg xmlns="http://www.w3.org/2000/svg"
                                                                       viewBox="0 0 24 24" class="gl-emote"
                                                                       style="pointer-events: none;"><circle
                                            class="gl-emote-bg" fill="#FFD885" cx="12" cy="12" r="10"></circle><path
                                            fill="#393939"
                                            d="M15.33 15.2a.8.8 0 01.7.66.85.85 0 01-.68.94h-6.2c-.24 0-.67-.26-.76-.7-.1-.38.17-.81.6-.9zm.35-7.2a1.6 1.6 0 011.5 1.86A1.6 1.6 0 1115.68 8zM8.32 8a1.6 1.6 0 011.21 2.73A1.6 1.6 0 118.33 8z"></path></svg></span>
                            <span data-value="4" class="starNour"><svg xmlns="http://www.w3.org/2000/svg"
                                                                       viewBox="0 0 24 24" class="gl-emote"
                                                                       style="pointer-events: none;"><circle
                                            class="gl-emote-bg" fill="#FFD885" cx="12" cy="12" r="10"></circle><path
                                            fill="#393939"
                                            d="M15.45 15.06a.8.8 0 11.8 1.38 8.36 8.36 0 01-8.5 0 .8.8 0 11.8-1.38 6.76 6.76 0 006.9 0zM15.68 8a1.6 1.6 0 011.5 1.86A1.6 1.6 0 1115.68 8zM8.32 8a1.6 1.6 0 011.21 2.73A1.6 1.6 0 118.33 8z"></path></svg></span>
                            <span data-value="5" class="starNour"><svg xmlns="http://www.w3.org/2000/svg"
                                                                       viewBox="0 0 24 24" class="gl-emote"
                                                                       style="pointer-events: none;"><circle
                                            class="gl-emote-bg" fill="#FFD885" cx="12" cy="12" r="10"></circle><path
                                            fill="#393939"
                                            d="M16.8 14.4c.32 0 .59.2.72.45.12.25.11.56-.08.82a6.78 6.78 0 01-10.88 0 .78.78 0 01-.05-.87c.14-.23.37-.4.7-.4zM15.67 8a1.6 1.6 0 011.5 1.86A1.6 1.6 0 1115.68 8zM8.32 8a1.6 1.6 0 011.21 2.73A1.6 1.6 0 118.33 8z"></path></svg></span>
                        </span>
                                </span>
                                </div>
                                <p>{{ evenement.description }}</p>


                                <div class="nicdark_space20"></div>
                                <div class="row">

                                    <div class="col col-md-6">
                                    <span class="gl-star-rating">

                                      </span>
                                        <a href="{{ path('evenement_showsingle', {'id': evenement.id}) }}"
                                           class="nicdark_press white nicdark_btn nicdark_bg_green medium  ">MORE
                                            INFO</a>
                                    </div>
                                    <div class="col col-md-6">
                                        <a href="{{ path('evenement_edit', {'id': evenement.id}) }}"
                                           class="nicdark_press white nicdark_btn nicdark_bg_orange medium  ">Modifier</a>
                                    </div>


                                    <div class="nicdark_space20"></div>

                                </div>
                            </div>

                            <a href="{{ path('commande_e_new', {'id': evenement.id}) }}"
                               class="grey nicdark_btn nicdark_bg_grey nicdark_border_grey  medium   nicdark_press"><i
                                        class="icon-basket"></i>Commander</a>
                        </div>

                    </div>

                </div>
            {% endfor %}

        </div>
        <!--end nicdark_container-->

    </section>
    <!--end section-->

    <!--start section-->
    {# <div class="nicdark_section">

        <!--start nicdark_container-->
        <div class="nicdark_container nicdark_clearfix">

            <div class="nicdark_space40"></div>

            <div class="grid grid_6 nicdark_aligncenter_iphoneland nicdark_aligncenter_iphonepotr">
                <a class="nicdark_disable_floatright_iphoneland nicdark_disable_floatright_iphonepotr nicdark_btn nicdark_bg_green medium right   white nicdark_press"><i class="icon-angle-left"></i>&nbsp;&nbsp;&nbsp;PREV</a>
            </div>
            <div class="grid grid_6 nicdark_aligncenter_iphoneland nicdark_aligncenter_iphonepotr">
                <a class=" nicdark_btn nicdark_bg_green medium   white nicdark_press">NEXT&nbsp;&nbsp;&nbsp;<i class="icon-angle-right"></i></a>
            </div>

            <div class="nicdark_space50"></div>

        </div>
        <!--end nicdark_container-->

    </div> #}

{% endblock %}
{% block extraJS %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/prism.min.js"
            integrity="sha512-YBk7HhgDZvBxmtOfUdvX0z8IH2d10Hp3aEygaMNhtF8fSOvBZ16D/1bXZTJV6ndk/L/DlXxYStP8jrF77v2MIg=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.23.0/plugins/autoloader/prism-autoloader.min.js"
            integrity="sha512-zc7WDnCM3aom2EziyDIRAtQg1mVXLdILE09Bo+aE1xk0AM2c2cVLfSW9NrxE5tKTX44WBY0Z2HClZ05ur9vB6A=="
            crossorigin="anonymous"></script>

    <script src="/FRONT/js/star-rating.js"></script>
    <script>
        toastr.options = {
            "positionClass": "toast-bottom-right",
        }
        //MEN HNA
        var starratingPrebuilt = new StarRating('.star-rating-prebuilt', {
            prebuilt: true,
            maxStars: 5,
            tooltip: 'Rate us'

        });
        $(".starNour").click(function () {
            $.get($(this).parent().attr("eventId") + "/editRating/" + $(this).attr("data-value"), function (data) {
                toastr.success("Rating changed!");
            });
            $(this).parent().parent().parent().parent().find(".nourRatingFinal").text("Rating: " + $(this).attr("data-value"));
            console.log("clicked " + $(this).attr("data-value"))
        });
        //LAHNE


        setTimeout(function () {

            toastr.info('There is a total of {{ nearEventsTotal }} events happening this week!');

        }, 5000);//alert after 5000 ms


    </script>
{% endblock %}
{# <h1>Evenement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_e</th>
                <th>Date_deb</th>
                <th>Date_fin</th>
                <th>Image_e</th>
                <th>Description</th>
                <th>Prix_e</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.nomE }}</td>
                <td>{{ evenement.dateDeb ? evenement.dateDeb|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ evenement.imageE }}</td>
                <td>{{ evenement.description }}</td>
                <td>{{ evenement.prixE }}</td>
                <td>
                    <a href="{{ path('evenement_show', {'id': evenement.id}) }}">show</a>
                    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('evenement_new') }}">Create new</a> #}

symfonyProject/templates/evenement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Nom_e</th>
                <td>{{ evenement.nomE }}</td>
            </tr>
            <tr>
                <th>Date_deb</th>
                <td>{{ evenement.dateDeb ? evenement.dateDeb|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Image_e</th>
                <td>{{ evenement.imageE }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ evenement.description }}</td>
            </tr>
            <tr>
                <th>Prix_e</th>
                <td>{{ evenement.prixE }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('evenement_index') }}">back to list</a>

    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">edit</a>
{% endblock %}