symfonyProject/src/Entity/Materiel.php
<?php

namespace App\Entity;

use App\Repository\MaterielRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=MaterielRepository::class)
 */
class Materiel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $nom;

    /**
     * @ORM\Column(type="string")
     */
    private $prenom;

    /**
     * @ORM\Column(type="string")
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $numtel;


    /**
     * @ORM\Column(type="float")
     * @Assert\Positive(
     * message="le prix ne doit pas etre negatif ou égale à 0")
     */
    private $prix_m;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Cette valeur ne doit pas être vide")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nom_materiel;

    /**
     * @ORM\ManyToOne(targetEntity=CategorieM::class, inversedBy="materiels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=CommandeM::class, inversedBy="materiel")
     */
    private $commandeM;






    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom): void
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * @param mixed $prenom
     */
    public function setPrenom($prenom): void
    {
        $this->prenom = $prenom;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getNumtel()
    {
        return $this->numtel;
    }

    /**
     * @param mixed $numtel
     */
    public function setNumtel($numtel): void
    {
        $this->numtel = $numtel;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrixM(): ?float
    {
        return $this->prix_m;
    }

    public function setPrixM(float $prix_m): self
    {
        $this->prix_m = $prix_m;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getNomMateriel(): ?string
    {
        return $this->nom_materiel;
    }

    public function setNomMateriel(string $nom_materiel): self
    {
        $this->nom_materiel = $nom_materiel;

        return $this;
    }


    public function getIdcategorie(): ?CategorieM
    {
        return $this->idcategorie;
    }

    public function setIdcategorie(?CategorieM $idcategorie): self
    {
        $this->idcategorie = $idcategorie;

        return $this;
    }

    public function getCategorie(): ?CategorieM
    {
        return $this->categorie;
    }

    public function setCategorie(?CategorieM $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    public function getCommandeM(): ?CommandeM
    {
        return $this->commandeM;
    }

    public function setCommandeM(?CommandeM $commandeM): self
    {
        $this->commandeM = $commandeM;

        return $this;
    }
}

symfonyProject/src/Form/MaterielType.php
<?php

namespace App\Form;

use App\Entity\CategorieM;
use App\Entity\Materiel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class MaterielType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('email')
            ->add('numtel')
            ->add('prix_m')
            ->add('description')
            ->add('nom_materiel')
            ->add('image',FileType::class,
                array('data_class'=>null,'required'=>false))

            ->add('categorie',EntityType::class,[
                'class'=>CategorieM::class,
                'choice_label'=>'nomCatM'
            ])


            ->add('Create', SubmitType::class)

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Materiel::class,
        ]);
    }
}

symfonyProject/src/Controller/MaterielController.php
<?php

namespace App\Controller;

use App\Entity\Materiel;
use App\Form\MaterielType;
use App\Repository\MaterielRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Filesystem\Exception\FileNotFoundException;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Dompdf\Dompdf;
use Dompdf\Options;



/**
 * @Route("/materiel")
 */
class MaterielController extends AbstractController

{
    /**
     * @Route("/", name="materiel_index", methods={"GET"})
     */
    public function index(MaterielRepository $materielRepository): Response
    {
        return $this->render('materiel/index.html.twig', [
            'materiels' => $materielRepository->findAll(),
        ]);
    }

    /**
     * @Route("/magasin", name="list-materiel", methods={"GET"})
     */
    public function liste(Request $request,MaterielRepository $materielRepository, PaginatorInterface $paginator): Response
    {
        $donnees = $this->getDoctrine()->getRepository(Materiel::class)->findAll();

        $materiel = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos materiels)
            $request->query->getInt('page', 1),3);

        return $this->render('materiel/magasin.html.twig', [
            'materiels' => $materiel,
        ]);
    }

    /**
     * @Route("/admin/materiels", name="admin-materiel", methods={"GET"})
     */
    public function materiels(MaterielRepository $materielRepository): Response
    {
        return $this->render('/materiel/admin/materiels.html.twig', [
            'materiels' => $materielRepository->findAll(),
        ]);
    }


    /**
     * @IsGranted ("ROLE_USER")
     * @Route("/new", name="materiel_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $materiel = new Materiel();
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file=$materiel->getImage();
            $uploads_directory=$this->getParameter('uploads_directory');
            $file_name=md5(uniqid())    . '.'   . $file->guessExtension();
            $file->move(
                $uploads_directory,
                $file_name
            );


            $materiel->setImage($file_name);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($materiel);
            $entityManager->flush();

            return $this->redirectToRoute('list-materiel', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('materiel/new.html.twig', [
            'materiel' => $materiel,
            'form' => $form->createView(),
        ]);


    }

    /**
     * @Route("/{id}", name="materiel_show", methods={"GET"})
     */
    public function show(Materiel $materiel): Response
    {
        return $this->render('materiel/show.html.twig', [
            'materiel' => $materiel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="materiel_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Materiel $materiel, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file=$materiel->getImage();
            $uploads_directory=$this->getParameter('uploads_directory');
            $file_name=md5(uniqid())    . '.'   . $file->guessExtension();
            $file->move(
                $uploads_directory,
                $file_name
            );
            $materiel->setImage($file_name);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('materiel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('materiel/edit.html.twig', [
            'materiel' => $materiel,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="materiel_delete", methods={"POST"})
     */
    public function delete(Request $request, Materiel $materiel, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$materiel->getId(), $request->request->get('_token'))) {
            $entityManager->remove($materiel);
            $entityManager->flush();
        }

        return $this->redirectToRoute('materiel_index', [], Response::HTTP_SEE_OTHER);
    }





    /**
     * @Route("/pdf/fatma", name="imprimer", methods={"GET"})
     */
    public function pdf(MaterielRepository $materielRepository): Response
    {

        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        $pdfOptions->set('isRemoteEnabled', true);

        $dompdf = new Dompdf($pdfOptions);

        $html = $this->renderView('materiel/pdf.html.twig', [
            'materiels' => $materielRepository->findAll(),
        ]);

        $dompdf->loadHtml($html);


        $dompdf->setPaper('A4', 'portrait');

        $dompdf->render();


        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);
    }



}

symfonyProject/templates/materiel/_delete_form.html.twig
<form method="post" action="{{ path('materiel_delete', {'id': materiel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ materiel.id) }}">
    <button class="btn">Supprimer</button>
</form>

symfonyProject/templates/materiel/_form.html.twig
{% block title %}Edit Materiel{% endblock %}
{% block body %}

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
{% endblock %}

symfonyProject/templates/materiel/edit.html.twig
{% block title %}Edit Materiel{% endblock %}

{% block body %}

    <h1>Edit Materiel</h1>

    {{ include('materiel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('materiel_index') }}">back to list</a>

    {{ include('materiel/_delete_form.html.twig') }}


{% endblock %}

symfonyProject/templates/materiel/index.html.twig
{% extends 'base-back.html.twig' %}

{% block body %}

    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>Afficher</h4>
                <ol class="breadcrumb">

                    <li class="breadcrumb-item active"><a href="#">tout les matériels</a></li>
                </ol>
            </div>
            <!-- row -->


            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Liste des catégories des matériels </h4>
                        </div>
                        <div class="card-body">
                            <div class="topbar-search">
                                <form>
                                    <label class="navbar-collapse">
                                        <input class="form-control" type="text" width="100px" height="100px" name="AfficherClasse"
                                               onkeyup="myFunction()" placeholder="Recherche " id="myInput">

                                        <i class="fa fa-search"></i></label>
                                </form>

                                <a class="btn btn-success" href="{{path('imprimer') }}">  PDF </a>
                                <div class="nicdark_space30"></div>
                            </div>
                            <div class="table-responsive">

                                <table id="materiel" class="display min-w850  dataTable no-footer">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Nom</th>
                                        <th>Prenom</th>
                                        <th>Email</th>
                                        <th>Numtel</th>
                                        <th>Prix_m</th>
                                        <th>Description</th>
                                        <th>Nom_materiel</th>
                                        <th>Image</th>
                                        <th>actions</th>
                                    </tr>

                                    </thead>
                                    <tbody id="myTable">

                                    {% for materiel in materiels %}
                                        <tr>
                                            <td>{{ materiel.id }}</td>
                                            <td>{{ materiel.nom }}</td>
                                            <td>{{ materiel.prenom }}</td>
                                            <td>{{ materiel.email }}</td>
                                            <td>{{ materiel.numtel }}</td>
                                            <td>{{ materiel.prixM }}</td>
                                            <td>{{ materiel.description }}</td>
                                            <td>{{ materiel.nomMateriel }}</td>
                                            <td><img src="{{ asset('uploads/'~materiel.image ) }}" alt="" width="50px" height="50px"/></td>

                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="12">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>


                                </table>
                                <div class="navigation">
                                    {#    {{ knp_pagination_render(utilisateurs,'@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',{'rounded': true,'size': 'small' }) }}
                                    #}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function myFunction() {
            var input, filter, table, tr, td, i, j, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("materiel");
            tr = table.getElementsByTagName("tr");
            //   alert(td.length);
            for (i = 0; i < tr.length; i++) {
                var rowContent = tr[i].textContent;
                rowContent = rowContent.replace(/[\s]+/g, ' ');
                //console.log(rowContent);

                if (rowContent) {
                    if (rowContent.toUpperCase().includes(filter)) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }

            }
        }


    </script>


{% endblock %}

symfonyProject/templates/materiel/magasin.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<div class="nicdark_site">
    <div class="nicdark_site_fullwidth nicdark_site_fullwidth_boxed nicdark_clearfix">




        <!--start section-->
        <section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img7" style="background-position: 50% 0px;">

            <div class="nicdark_filter">

                <!--start nicdark_container-->
                <div class="nicdark_container nicdark_clearfix">

                    <div class="nicdark_space100"></div>
                    <div class="nicdark_space100"></div>

                    <div class="nicdark_space70"></div> <!--for header 1-->

                    <div class="grid grid_6">
                        <h1 class="white subtitle">MAGASIN</h1>
                    </div>


                    <div class="nicdark_space40"></div>
                    <div class="nicdark_space40"></div>

                </div>
                <!--end nicdark_container-->

            </div>

        </section>
        <!--end section-->



        <!-- archive shop start -->
        <!--start section-->
        <section class="nicdark_section">

            <!--start nicdark_container-->
            <div class="nicdark_container nicdark_clearfix">

                <div class="nicdark_space50"></div>

                <div class="grid grid_3">


                </div>
                {% for materiel in materiels %}
                <div class="grid grid_3">

                    <!-- start product-->
                    <div class="nicdark_archive1 nicdark_border_grey nicdark_sizing  ">



                        <img src="{{ asset('uploads/'~materiel.image ) }}"alt="" width="50px" height="50px"/>

                        <div class="nicdark_textevidence nicdark_bg_greydark">
                            <h4 class="white nicdark_margin20">{{ materiel.nomMateriel}}</h4>
                        </div>


                        <div class="nicdark_textevidence">
                            <div class="nicdark_margin20">
                                <p>{{ materiel.prixM }} DT</p>
                                <div class="nicdark_space20"></div>
                                <a href="{{ path('commande_m_new', {'id': materiel.id})  }}" class="grey nicdark_btn nicdark_bg_grey nicdark_border_grey  medium   nicdark_press"><i class="icon-basket"></i>&nbsp;&nbsp;&nbsp;Acheter</a>
                            </div>
                        </div>

                    </div>

                    <!-- end product-->
                </div>
                {% endfor %}






            </div>
            <!--end nicdark_container-->
            {{ knp_pagination_render(materiels,'@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',{'rounded': true,'size': 'small' }) }}

    </div>
        </section>
        <!--end section-->






        <!-- archive shop end -->

        <!--end-->

        <!--<div class="nicdark_space3 nicdark_bg_gradient"></div>-->



       </div>
</div>

{% endblock %}

symfonyProject/templates/materiel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Materiel{% endblock %}

{% block body %}
    <h1>Create new Materiel</h1>

    <section id="nicdark_parallax_title" class="nicdark_section nicdark_imgparallax nicdark_parallaxx_img5">

        <div class="nicdark_filter greydark">

            <!--start nicdark_container-->
            <div class="nicdark_container nicdark_clearfix">

                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>
                <div class="nicdark_space100"></div>

            </div>
            <!--end nicdark_container-->

        </div>

    </section>
    <!--end section-->
    <!--start nicdark_container-->
    <div class="nicdark_container nicdark_clearfix">

        <div class="nicdark_space40"></div>


        <!--title-->
        <div class="nicdark_alerts nicdark_bg_green  ">
            <p class="white nicdark_size_medium"><i class="bi bi-arrow-down-circle">
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" line-height="1em" fill="currentColor"
                         class="bi bi-arrow-down-circle" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                              d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
                    </svg>
                </i>
                <strong>DEPOSER VOTRE MATERIELS :</strong></p>
        </div>
        <!--title-->
        <div class="card-body">
            <div class="nicdark_space5"></div>
            <div class="nicdark_space20"></div>
            <div class="nicdark_space20"></div>
            {{ form_start(form) }}
            <div class="form-row">
                <div class="form-group col-md-6">

                    {{ form_widget(form.nom,{'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle",'placeholder':'Votre Nom'}}) }}
                </div>
                <div class="form-group col-md-6">

                    {{ form_widget(form.prenom,{'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey large subtitle",'placeholder':'Votre Prénom'}}) }}
                </div>
            </div>


            <div class="form-row">
                <div class="form-group col-md-6">

                    {{ form_errors(form.email) }}
                    {{ form_widget(form.email, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle",'placeholder':'Votre Email'}}) }}
                </div>
                <div class="form-group col-md-6">

                    {{ form_errors(form.numtel) }}
                    {{ form_widget(form.numtel, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle",'placeholder':'Téléphone'}}) }}
                </div>
            </div>

            {# <div class="nicdark_space20"></div>
                <p>CATEGORIE MATERIEL:</p>
                <div class="nicdark_space5"></div>
                <label for="cat" ></label>
                <select id="cat" class="nicdark_bg_grey nicdark_border_grey   grey small subtitle" type="option" value="" >
                    <option value="">CHOIX</option>
                    <optgroup label="" >
                        <option value="">Tente et abris</option>
                        <option value="">Vêtement</option>
                        <option value="">Couchage</option>
                        <option value="">Mobilier de camping</option>
                        <option value="">Boire et manger</option>
                        <option value="">Autres equipements</option>
                    </optgroup>
                </select>
                <div class="nicdark_space20"></div>
                {{ form_errors(form.IdCatM) }}
                {{ form_widget(form.IdCatM, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle"}})}}
                <div class="nicdark_space20"></div> #}


            <div class="form-row">
                <div class="form-group col-md-6">

                    <div class="nicdark_space20"></div>
                    {{ form_errors(form.nom_materiel) }}
                    {{ form_widget(form.nom_materiel, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle",'placeholder':'Matériel'}}) }}
                </div>
                <div class="form-group col-md-6">

                    {{ form_errors(form.description) }}
                    {{ form_widget(form.description, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle",'placeholder':'Description'}}) }}
                </div>
            </div>




            <div class="form-row">
                <div class="form-group col-md-6">

                    <div class="nicdark_space20"></div>
                    {{ form_errors(form.prix_m) }}
                    {{ form_widget(form.prix_m, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey medium subtitle",'placeholder':'Prix'}})}}
                </div>
                <div class="form-group col-md-6">
                    <label>Catégorie du matériel</label>
                    {{ form_errors(form.categorie) }}
                    {{ form_widget(form.categorie, {'attr':{'class':"nicdark_bg_grey nicdark_border_grey   grey small subtitle"}}) }}
                </div>
            </div>


            <div class="nicdark_space5"></div>
            <div class="nicdark_space5"></div>



            {{ form_end(form) }}

        </div>
    </div>


    </div>

    </div>
{% endblock %}

symfonyProject/templates/materiel/pdf.html.twig
<p class="text-center", style="color:#00aced ;text-align: center; font-size: 45px "><strong>Matériels ajoutés</strong> </p>

<table class="border border-primary", style=" margin-left: 2cm; margin-right: 2cm ;padding-left: 1cm; padding-right: 1cm;padding-top: 1cm; background-color:#D4E6F1; border: #0c4382; align:center ">
    <thead style="background-color: #00aced">
    <tr class="table-primary">
        <th>Id</th>
        <th>Nom</th>
        <th>Prenom</th>
        <th>Email</th>
        <th>Prix_m</th>
        <th>Nom_materiel</th>
    </tr>
    </thead>
    <tbody>
    {% for materiel in materiels %}
        <tr class="table-light">
            <td >{{ materiel.id }}</td>
            <td>{{ materiel.nom }}</td>
            <td>{{ materiel.prenom }}</td>
            <td>{{ materiel.numtel }}</td>
            <td>{{ materiel.prixM }}</td>
            <td>{{ materiel.nomMateriel }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="6">no records found</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

symfonyProject/templates/materiel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Materiel{% endblock %}

{% block body %}
    <div class="nicdark_space100"></div>
    <div class="nicdark_space80"></div>

    <h1>Materiel</h1>
    <table class="nicdark_table extrabig nicdark_bg_white " >
        <thead  >
          <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Email</th>
            <th>Numtel</th>
            <th>Prix_m</th>
            <th>Description</th>
            <th>Nom materiel</th>
            <th>Image</th>
            <th>actions</th>
          </tr>
        </thead>

        <tbody >
            <tr>
                <td >{{ materiel.id }}</td>
                <td >{{ materiel.nom }}</td>
                <td >{{ materiel.prenom }}</td>
                <td >{{ materiel.email }}</td>
                <td >{{ materiel.numtel }}</td>
                <td>{{ materiel.prixM }}</td>
                <td >{{ materiel.description }}</td>
                <td >{{ materiel.nomMateriel }}</td>
                <td ><img src="{{ asset('uploads/'~materiel.image ) }}"alt="" width="50px" height="50px"/></td>
            <td > <a href="{{ path('materiel_index') }}" class="nicdark_bg_grey nicdark_border_grey   grey small subtitle">Retour à la liste </a>
    <a href="{{ path('materiel_edit', {'id': materiel.id}) }}" class="nicdark_bg_grey nicdark_border_grey   grey small subtitle">Modifier</a> </td>
            </tr>

        </tbody>
    </table>
    {{ include('materiel/_delete_form.html.twig') }}

        <div class="nicdark_space100"></div>
{% endblock %}