symfonyProject/src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="sent")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="received")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $recipient;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Utilisateur
    {
        return $this->sender;
    }

    public function setSender(?Utilisateur $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Utilisateur
    {
        return $this->recipient;
    }

    public function setRecipient(?Utilisateur $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

symfonyProject/src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Messages;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control "
                ]
            ])
            ->add('message', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class, [
                "class" => Utilisateur::class,
                "choice_label" => "email",
                "attr" => [
                    "class" => "form-control",
                    "rows"=>"15"
                ]
            ])
            ->add('envoyer', SubmitType::class, [
                "attr" => [
                    "class" => "btn btn-primary"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

symfonyProject/src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index(): Response
    {
        return $this->render('messages/received.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }

    /**
     * @Route("/send", name="send")
     */
    public function send(Request $request): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessagesType::class, $message);
        
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();

            $this->addFlash("message", "Message envoyé avec succès.");
            return $this->redirectToRoute("sent");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    }


    /**
     * @Route("/sent", name="sent")
     */
    public function sent(): Response
    {
        return $this->render('messages/sent.html.twig');
    }

    /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message): Response
    {
        $message->setIsRead(true);
        $em = $this->getDoctrine()->getManager();
        $em->persist($message);
        $em->flush();

        return $this->render('messages/read.html.twig', compact("message"));
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute("received");
    }
}

symfonyProject/templates/messages/messagerie.html.twig
<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from welly.dexignzone.com/xhtml/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 12 Feb 2022 12:36:49 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon icon -->
    {% block css %}
        <!-- Datatable -->
        <link href="{{ asset('/BACK/vendor/datatables/css/jquery.dataTables.min.css') }}" rel="stylesheet">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('/BACK/images/favicon.png') }}">
        <link href="{{ asset('/BACK/vendor/jqvmap/css/jqvmap.min.css') }}" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('/BACK/vendor/chartist/css/chartist.min.css') }}">
        <link href="{{ asset('/BACK/vendor/bootstrap-select/dist/css/bootstrap-select.min.css') }}" rel="stylesheet">
        <link href="{{ asset('/BACK/vendor/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css') }}" rel="stylesheet">
        <link href="{{ asset('/BACK/css/style.css') }}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&amp;family=Roboto:wght@100;300;400;500;700;900&amp;display=swap" rel="stylesheet">

        <style>



            * {
                padding: 0;
                margin: 0;
                box-sizing: border-box;
            }

            ul {
                list-style: none;
            }

            button {
                border: none;
                background: transparent;
                outline: none;
                cursor: pointer;
            }

            button:active {
                color: black;
            }

            a {
                text-decoration: none;
                color: black;
            }

            body {
                font: normal 16px/1.5 'poppins', sans-serif;
            }


            /* .top-banner
            –––––––––––––––––––––––––––––––––––––––––––––––––– */

            .top-banner {
                display: flex;
                width: calc(100% - 150px);
                height: 100vh;
                transform: translateX(150px);

            }

            .top-banner-overlay {
                display: flex;
                flex-direction: column;
                justify-content: center;
                width: 350px;
                padding: 20px;
                transition: transform .7s;
                color: white;
                background: rgba(0, 0, 0, .7);
            }

            .top-banner-overlay.is-moved {
                transform: translateX(350px);
            }

            .top-banner-overlay.is-moved::before {
                content: '';
                position: absolute;
                top: 0;
                bottom: 0;
                right: 100%;
                width: 20px;
                box-shadow: 0 0 10px black;
            }

            .top-banner-overlay p {
                font-size: 1rem;
                margin-top: 10px;
            }

            .top-nav li + li {
                margin-top: 7px;
            }


            /* .menu-wrapper
            –––––––––––––––––––––––––––––––––––––––––––––––––– */
            .top-nav .menu-wrapper {
                position: fixed;
                top: 0;
                left: 0;
                bottom: 0;
                width: 300px;
                padding: 20px;
                transform: translateX(-200px);
                transition: transform .7s;
                background: #ace5c1;
            }

            .top-nav .menu-wrapper.is-opened {
                transform: translateX(150px);
            }

            .top-nav .menu-wrapper .menu {
                opacity: 0;
                transition: opacity .4s;

            }

            .top-nav .menu-wrapper.is-opened .menu {
                opacity: 1;
                transition-delay: .6s;

            }

            .top-nav .menu-wrapper .menu a {
                font-size: 1.2rem;

            }

            .top-nav .menu-wrapper .sub-menu {
                padding: 10px 0 0 7px;
            }

            .top-nav .menu-wrapper .menu-close {
                position: absolute;
                top: 20px;
                right: 20px;
                font-size: 1.6rem;
                color: #FFFFFF;
            }


            /* .fixed menu
            –––––––––––––––––––––––––––––––––––––––––––––––––– */

            .top-nav .fixed-menu {
                position: fixed;
                top: 0;
                left: 0;
                bottom: 0;
                display: flex;
                flex-direction: column;
                width: 150px;
                padding: 20px;
                background: #76b28e;


            }

            .top-nav .fixed-menu .menu-open {
                font-size: 1.8rem;
                text-align: left;
                margin: 30px 0 auto;
                width: 28px;
                color:#FFFFFF;
            }










        </style>


    {% endblock %}
</head>
<body>

<section class="top-banner">

    <div class="container-fluid">
        <div class="page-titles read-content-body">
            <h1>BOITE MESSAGERIE</h1>

        </div>
        <!-- row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="email-left-box generic-width px-0 mb-5">
                            <div class="p-0">
                                <a href="{{ path('send') }}" class="btn btn-primary btn-block">Envoyer un message</a>
                            </div>
                            <div class="mail-list mt-4">
                                <a href="{{ path('received') }}" class="list-group-item active">
                                    <i class="fa fa-inbox font-18 align-middle mr-2"></i> Boite de réception

                                </a>
                                <a href="{{ path('sent')}}" class="list-group-item">
                                    <i class="fa fa-paper-plane font-18 align-middle mr-2"></i>Envoyé
                                </a>
                                <a href="javascript:void()" class="list-group-item">
                                    <i class="fa fa-star font-18 align-middle mr-2"></i>Important
                                    <span class="badge badge-danger badge-sm text-white float-right">47</span>
                                </a>

                                <a href="javascript:void()" class="list-group-item">
                                    <i class="fa fa-trash font-18 align-middle mr-2"></i>Trash
                                </a>
                            </div>

                        </div>
                      {% block body %}

                        {%endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>
<nav class="top-nav">
    <div class="menu-wrapper">
        <ul class="menu">
            <li>
                <a href="{{ path('accueil') }}">Accueil</a>
            </li>

            <li>
                <a href="{{ path('utilisateur_show',{'id':app.user.id}) }}">Profil</a>
            </li>

            <li>
                <a href="">contact</a>
            </li>
        </ul>
        <button class="menu-close" aria-label="close menu">✕</button>
    </div>
    <div class="fixed-menu">
        <h2 style="color: #FFFFFF">GO CAMP</h2>
        <button class="menu-open" aria-label="open menu">☰</button>
        <ul >

            <li>
                <a href="{{ path('app_logout') }}"><h6 style="color: #FFFFFF">Déconnexion</h6></a>
            </li>

        </ul>
    </div>
</nav>







{% block js %}
    <script src="/BACK/vendor/global/global.min.js"></script>
    <script src="/BACK/vendor/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="/BACK/vendor/chart.js/Chart.bundle.min.js"></script>
    <script src="/BACK/js/custom.min.js"></script>
    <script src="/BACK/js/deznav-init.js"></script>
    <script src="/BACK/vendor/bootstrap-datetimepicker/js/moment.js"></script>
    <script src="/BACK/vendor/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
    <!-- Chart piety plugin files -->
    <script src="/BACK/vendor/peity/jquery.peity.min.js"></script>

    <!-- Apex Chart -->
    <script src="/BACK/vendor/apexchart/apexchart.js"></script>

    <!-- Dashboard 1 -->
    <script src="/BACK/js/dashboard/dashboard-1.js"></script>
    <script>
        $(function () {
            $('#datetimepicker1').datetimepicker({
                inline: true,
            });
        });
    </script>


    <script>
        const menuOpen = document.querySelector(".top-nav .menu-open");
        const menuClose = document.querySelector(".top-nav .menu-close");
        const menuWrapper = document.querySelector(".top-nav .menu-wrapper");
        const topBannerOverlay = document.querySelector(".top-banner-overlay");

        function toggleMenu() {
            menuOpen.addEventListener("click", () => {
                menuWrapper.classList.add("is-opened");
                topBannerOverlay.classList.add("is-moved");
            });

            menuClose.addEventListener("click", () => {
                menuWrapper.classList.remove("is-opened");
                topBannerOverlay.classList.remove("is-moved");
            });
        }

        toggleMenu();



    </script>
{% endblock %}
</body>
</html>

symfonyProject/templates/messages/read.html.twig
{% extends 'messages/messagerie.html.twig' %}

{% block body %}
							<section class="container">


								<div class="row">
									<div class="col">
										<div class="col">
											<div class="col">
							<div class="read-content">
								<div class="media pt-3 d-sm-flex d-block justify-content-between">
									<div class="clearfix mb-3 d-flex">

										<img src="{{ asset('uploads/image/' ~ app.user.image) }}" class="mr-3 rounded" width="50" alt="">
										<div class="media-body mr-2">
											<h5 class="text-primary mb-0 mt-1">De: {{ message.sender.nom }} {{ message.sender.prenom }}</h5>
											<p class="mb-0">{{ message.sender.email }}</p>
										</div>
									</div>
									<div class="clearfix mb-3">
										<a href="javascript:void()" class="btn btn-primary px-3 light"><i class="fa fa-reply"></i> </a>
										<a href="javascript:void()" class="btn btn-primary px-3 light ml-2"><i class="fa fa-long-arrow-right"></i> </a>
										<a href="javascript:void()" class="btn btn-primary px-3 light ml-2"><i class="fa fa-trash"></i></a>
									</div>
								</div>
								<hr>
								<div class="media mb-2 mt-3">
									<div class="media-body"><span class="pull-right">{{ message.createdAt|date }}</span>
										<h5 class="my-1 text-primary">
											Objet:
											{{ message.title }}
										</h5>
										<p class="read-content-email">
											To: Me
									</div>
								</div>
								<div class="read-content-body">
									{{ message.message }}
								</div>



							</div>
									</div>
										</div>
</div>
							</section>

{% endblock %}

symfonyProject/templates/messages/received.html.twig
{% extends 'messages/messagerie.html.twig' %}

{% block body %}

<section class="container">


	<div class="row">
		<div class="col">
			<div class="col-12">
				<p>Vous avez reçu
					{{ app.user.received|length }}
					messages</p>
			</div>
			{% for message in app.user.received %}
	<div class="email-list mt-3">
		<div class="message">
			<div>

				<div class="d-flex message-single">
					<div class="pl-1 align-self-center">
						<div class="custom-control custom-checkbox">
							<a href="{{ path("delete", {id: message.id}) }}">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
									<path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
								</svg>
							</a>
						</div>
					</div>
					<div class="ml-2">
						<button class="border-0 bg-transparent align-middle p-0"><i class="fa fa-star" aria-hidden="true"></i></button>
					</div>
				</div>
				<a href="{{ path("read", {id: message.id}) }}" class="col-mail col-mail-2">

					{% set bold = "" %}
					{% if message.isRead == 0 %}
						{% set bold = "fw-bold" %}
					{% endif %}
					<div class="subject"><strong>{{ message.sender.email }}</strong> , {{ message.title }} - {{ message.message }}</div>
					<div class="date">{{ message.createdAt|date }}</div>
					<div >

					</div>

				</a>



			</div>

		</div>
	</div>
			{% endfor %}
		</div>
	</div>
</section>

{% endblock %}

symfonyProject/templates/messages/send.html.twig
{% extends 'messages/messagerie.html.twig' %}


{% block body %}

<section class="container">
    <div class="row">
        <div class="col">
            <div class="col">
                <div class="col">
            <h1></h1>
            {{ form_start(form) }}

                    <div class="form-group">
                        <label>A:</label>
                        {{form_widget(form.recipient)}}
                    </div>
                    <div class="form-group">
                        <label>Objet :</label>
                    {{form_widget(form.title)}}
                    </div>
                    <div class="form-group">
                        <label>Message:</label>
                    {{form_widget(form.message)}}
                    </div>
            {{ form_end(form) }}

                </div></div>
        </div>
    </div>
</section>

{% endblock %}

symfonyProject/templates/messages/sent.html.twig
{% extends 'messages/messagerie.html.twig' %}

{% block body %}

	<section class="container">


		<div class="row">
			<div class="col">
				<div class="col-12">
					<p>Vous avez envoyé
						{{ app.user.sent|length }}
						messages</p>
				</div>
				{% for message in app.user.sent %}
					<div class="email-list mt-3">
						<div class="message">
							<div>

								<div class="d-flex message-single">
									<div class="pl-1 align-self-center">
										<div class="custom-control custom-checkbox">
											{# code supp message #}
										</div>
									</div>
									<div class="ml-2">
										<button class="border-0 bg-transparent align-middle p-0"><i class="fa fa-star" aria-hidden="true"></i></button>
									</div>
								</div>
								<a href="{{ path("read", {id: message.id}) }}" class="col-mail col-mail-2">
									{% set bold = "" %}
									{% if message.isRead == 0 %}
										{% set bold = "fw-bold" %}
									{% endif %}
									<div class="subject"><strong>{{ message.sender.email }}</strong> , {{ message.title }} - {{ message.message }}</div>
									<div class="date">{{ message.createdAt|date }}</div>
									<div >

									</div>

								</a>



							</div>

						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>

{% endblock %}